### ISSUE TITLE
Boot fails in VirtualBox

### ISSUE THREAD

**Issue by faddat** [google/netboot#51] opened 2017-12-16 22:22 UTC
![screenshot from 2017-12-16 17-17-57](https://user-images.githubusercontent.com/7142025/34074810-58134f6c-e285-11e7-9a40-3025ece2f384.png)

I was successfully using pixiecore previously in the same setup. This began to happen, and I don't know why. Now, I have reinstalled my test environment (pixiecore and virtualbox) and am still getting it. Anyone have any idea why this is happening?

Ubuntu 17.10 desktop running virtualbox with a bridged network adapter. 

Thanks!

**Comment by faddat** [comment] 2017-12-17 19:02
I'm going to leave this open, mostly because it's very strange, but I think that it is caused by a bug in virtualbox, documented here:

https://github.com/coreos/tectonic-installer/issues/932

When I changed the configuration to metal booting from a raspberry pi, there were no problems. Mostly I'm leaving this open in case anyone can give insight into what happened here.  It's really got me flummoxed.

**Comment by danderson** [comment] 2017-12-17 21:32
Thanks for the bug report!

What a strange bug, and thank you for tracking down the root cause!

It's been a while since I hacked on Pixiecore, but I *thought* I chainloaded to pixiecore's embedded copy of iPXE precisely so that I could boot knowing exactly what iPXE features are available, instead of relying on the vendor's PXE implementation... It's possible that Virtualbox's copy of iPXE is good enough that Pixiecore thinks it can skip that step, only to fail immediately after...

**Comment by danderson** [comment] 2017-12-25 03:19
So, I think I can actually fix this in Pixiecore.

The ProxyDHCP server has a piece of logic where it checks if the booting client is iPXE, and if that iPXE supports HTTP. If yes, then it skips straight to serving the iPXE boot file. If not, then it first chainloads to our embedded iPXE.

A quick fix would be to just also check for bzImage support, which is one of the things listed in the iPXE DHCP option, and chainload to the Pixiecore-provided iPXE if that support is not present.

A slightly longer fix is to unconditionally chainload to Pixiecore's builtin iPXE, so that we always chainload to a "known" set of features instead of checking for individual feature support. This is a bit more complicated because we need a way to detect that the client is _our_ iPXE as opposed to any iPXE. iPXE supports setting a custom client name, so we could use that, but I'll have to dig more into how that works. It also makes it more complex to provide your own iPXE images in pixiecore-apache2, but I think it's probably time to declare that dead, honestly.

**Comment by danderson** [comment] 2017-12-25 03:42
@faddat Could you test the latest pixiecore code against your virtualbox system? AFAICT, the change I just pushed should be enough to make it boot correctly, but I'd love confirmation before I go deeper into the permanent fix. Thanks!

**Comment by danderson** [comment] 2017-12-25 04:52
@faddat And if possible, could you also test the code in the bug-51 branch? That branch unconditionally chainloads to pixiecore's embedded iPXE, so if I got it right, it should "fix" your virtualbox issue. Let me know if it works, and I'll merge into master.

**Comment by faddat** [comment] 2017-12-31 18:00
yes :)!  

I'll be happy to do both!

I'm also going to post another really odd issue.

**Comment by faddat** [comment] 2017-12-31 18:38
Branch bug-51 seems to be effected by #52. 

![image](https://user-images.githubusercontent.com/7142025/34463615-90984648-ee2f-11e7-8c34-c6135a1fa688.png)

The tell is of course that the machine's mac address is coming up as a filename. The last thing I need to do to be 100% sure that #52 is actually a regression is run one of the old (october?) armv7 binaries from packagecloud on our trusty raspberry pi and see if it makes boot happen.

**Comment by danderson** [comment] 2017-12-31 20:13
Updated #52, there's some weirdness that suggests the problem is in your environment and not in the code changes (I hope so, because otherwise I have _no_ idea how my Dec 24 changes are causing this failure...)

**Comment by danderson** [comment] 2018-01-01 23:28
Okay, the Virtualbox boot can be fixed by doing two things:

1. Unconditionally chainload to Pixiecore's embedded iPXE, so that we have all the features we need.
2. Chainload using ipxe.pxe instead of undionly.kpxe. The undionly stack causes network configuration failures when you chainload ipxe->ipxe.

Open question: I need to check that ipxe.pxe can reliably boot bare metal as well as ipxe-based VMs. I've tested a VM that uses Intel's UNDI stack, and that seemed to work... But testing with a real machine would make me feel better.

**Comment by danderson** [comment] 2018-01-02 08:03
@faddat Could you test the bug-51 branch on your setup? I've tested on a wide variety of systems that I have access to, and I think this fixes all the issues we encountered in this bug, but confirmation would be great before I merge into master.

**Closed** 2018-01-16 03:18 UTC
Labels: bug
